const projects = [
  {
    id: 1,
    module: "fundaments",
    name: "Project lessons learned",
    link: "https://deboraserra.github.io/Project-lessons-learned/project-block3.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/lessonsLearned.png?raw=true",
  },
  {
    id: 2,
    module: "fundaments",
    name: "Project Playground Functions",
    link: "https://github.com/DeboraSerra/Trybe-exercises/tree/main/Module1_fundaments/Block4/Project-playground-functions",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/playground.jpeg?raw=true",
  },
  {
    id: 3,
    name: "Project Pixel Art",
    module: "fundaments",
    link: "https://deboraserra.github.io/Project-pixel-art/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/pixelArt.png?raw=true",
  },
  {
    id: 4,
    module: "fundaments",
    name: "Project To Do List",
    link: "https://deboraserra.github.io/Project-to-do-list/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/ToDoList.png?raw=true",
  },
  {
    id: 5,
    module: "fundaments",
    name: "Project Mystery Letter",
    link: "https://deboraserra.github.io/Project-mystery-letter/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/MysteryLetter.png?raw=true",
  },
  {
    id: 6,
    module: "fundaments",
    name: "Project Meme Generator",
    link: "https://deboraserra.github.io/Project-meme-generator/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/MemeGenerator.png?raw=true",
  },
  {
    id: 7,
    module: "fundaments",
    name: "Project Color Guess",
    link: "https://deboraserra.github.io/Project-color-guess/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/ColorGuess.png?raw=true",
  },
  {
    id: 8,
    module: "fundaments",
    name: "Project Trybewarts",
    link: "https://deboraserra.github.io/Project-Trybewarts/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/TrybeWarts.png?raw=true",
  },
  {
    id: 9,
    module: "personal",
    name: "Clock",
    link: "https://deboraserra.github.io/Clock/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/Clock.png?raw=true",
  },
  {
    id: 10,
    module: "fundaments",
    name: "Project Zoo Functions",
    link: "https://github.com/DeboraSerra/DeboraSerra.github.io/tree/main/Project-zoo-functions",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/zoofunctions.jpeg?raw=true",
  },
  {
    id: 11,
    module: "fundaments",
    name: "Project Shopping Cart",
    link: "https://deboraserra.github.io/Project-shopping-cart/index.html",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/ShoppingCart.png?raw=true",
  },
  {
    id: 12,
    module: "frontEnd",
    name: "Project Solar System",
    link: "https://deboraserra.github.io/project-solar-system/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/SolarSystem.png?raw=true",
  },
  {
    id: 13,
    module: "frontEnd",
    name: "Project Tryunfo",
    link: "https://deboraserra.github.io/project-tryunfo/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/Tryunfo.png?raw=true",
  },
  {
    id: 14,
    module: "personal",
    name: "Project Stopwatch",
    link: "https://deboraserra.github.io/stopwatch/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/Stopwatch.png?raw=true",
  },
  {
    id: 15,
    module: "frontEnd",
    name: "Project TrybeTunes",
    link: "https://deboraserra.github.io/project-trybe-tunes/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/Trybetunes.png?raw=true",
  },
  {
    id: 16,
    module: "frontEnd",
    name: "Project FrontEnd Online Store (developed in group)",
    link: "https://deboraserra.github.io/project-online-store/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/OnlineStore.png?raw=true",
  },
  {
    id: 17,
    module: "frontEnd",
    name: "Project Trybewallet",
    link: "https://deboraserra.github.io/project-trybewallet/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/trybewallet.png?raw=true",
  },
  {
    id: 18,
    module: "frontEnd",
    name: "Project Trivia Game (Developed in group)",
    link: "https://deboraserra.github.io/project-trivia-game/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/trivi-game.png?raw=true",
  },
  {
    id: 19,
    module: "frontEnd",
    name: "Project Star Wars Planets",
    link: "https://deboraserra.github.io/project-starwars-planets/",
    src: "https://github.com/DeboraSerra/portfolio/blob/master/src/images/Starwars.png?raw=true",
  },
];

export default projects;
